name: Deploy to GitHub Pages

on:
  name: Deploy to GitHub Pages


            - name: Setup Pages
              uses: actions/configure-pages@v3

      - name: Copy site files to public
        run: |
          mkdir -p public
          cp index.html public/
          if [ -f qigong.html ]; then cp qigong.html public/; fi
          if [ -d images ]; then cp -r images public/; fi

            - name: Upload to Pages
              uses: actions/upload-pages-artifact@v3

              with:
                path: public

            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
