name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev
      - staging
      - prod

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build site into branch-specific folder
        run: |
          mkdir -p public
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
          mkdir -p public/$BRANCH_NAME
          cp -r * public/$BRANCH_NAME/ || true

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
