name: Deploy to GitHub Pages

on:
  name: Deploy to GitHub Pages

<<<<<<< HEAD
=======
permissions:
  contents: write
  pages: write
  id-token: write
>>>>>>> 122d062 (Preserve all branch folders in GitHub Pages deployment)

            - name: Setup Pages
              uses: actions/configure-pages@v3

      # Keep previously deployed branch folders so we don't overwrite
      - name: Download existing Pages artifact
        run: |
          git clone --depth=1 https://github.com/${{ github.repository }} temp-pages
          mv temp-pages/public ./ || mkdir -p public
          rm -rf temp-pages

      - name: Copy current branch site files
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
          mkdir -p public/$BRANCH_NAME
          cp index.html public/$BRANCH_NAME/
          if [ -f qigong.html ]; then cp qigong.html public/$BRANCH_NAME/; fi
          if [ -d images ]; then cp -r images public/$BRANCH_NAME/; fi
          if [ -d css ]; then cp -r css public/$BRANCH_NAME/; fi
          if [ -d js ]; then cp -r js public/$BRANCH_NAME/; fi

            - name: Upload to Pages
              uses: actions/upload-pages-artifact@v3

              with:
                path: public

            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
